### ISSUE TITLE
Issues with scandinavian characters

### ISSUE THREAD

**Issue by JuhQ** [geelen/typeslab#2]
It seems that the line height is wrong when using scandinavian characters, ä, ö, å for example.

![Scandinavian character issue](http://i.imgur.com/CAbNowJ.png)

**Comment by geelen** [comment]
Thanks for submitting. I need to either decide to come up with a strategy for predicting when this would occur (any diacritic above a capital letter) or develop a way to understand the real extent of a rendered piece of text. But I'll fix it!

**Comment by toabi** [comment]
Jip. +1

**Comment by ericol** [comment]
Same thing with spanish accentuated chars.

**Comment by ErtugKaya** [comment]
Beware that some characters have diacritics below. Here are some Turkish chars.

![image](https://cloud.githubusercontent.com/assets/4015159/7132266/4b322496-e290-11e4-9e1f-2efcb5d5579e.png)

I guess, you should measure character heights.

**Comment by geelen** [comment]
Fixed as of https://github.com/geelen/typeslab/pull/7

Thanks for letting me know about this!

**Comment by toabi** [comment]
Jey, much better. I just found some small special case: For those characters there is no font-combination where all letters are included and the ť hangs out. 

![Issue](http://i.imgur.com/TBmBNTW.png)

**Comment by geelen** [comment]
Yeah, that's a different bug - canvas has a `measureText` function which is supposed to give me a real width of the rendered text, but it doesn't. I might use the same logic for depth checking as I do for width-checking, shouldn't be too hard, but I won't have time to fix it for a while. Anyone feel like throwing a PR at me? The lines in question are here: https://github.com/geelen/typeslab/blob/master/src/lib/models/line-metrics.js#L15-L25

I'd love to avoid calculating the depth twice, but I don't see how. In the use-case above, the line doesn't need to be resized, just shifted left. Maybe that case is easier to deal with...
