### ISSUE TITLE
Error while building the project

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [geelen/typeslab#3]
Hi, I have cloned the repository. Trying to build using gulp. But failed with the following error message.

> [18:36:06] Using gulpfile ~/Code/cloned/typeslab/gulpfile.js
[18:36:06] Starting 'jspm-bundle'...
[18:36:07] Starting 'html'...
[18:36:07] Starting 'misc'...
[18:36:07] Finished 'html' after 64 ms
[18:36:07] Finished 'misc' after 42 ms
     Building the single-file sfx bundle for lib/main...

> err  Error: Error loading "lib/main" at file:/home/pras/Code/cloned/typeslab/src/lib/main.js
     Error loading "npm:babel@4.7.16" at file:/home/pras/Code/cloned/typeslab/src/jspm_packages/npm/babel@4.7.16.js
     ENOENT, open '/home/pras/Code/cloned/typeslab/src/jspm_packages/npm/babel@4.7.16.js'
[18:36:08] 'jspm-bundle' errored after 1.5 s
[18:36:08] Error in plugin 'gulp-shell'
Message:
    Command `jspm bundle-sfx lib/main dist/bundle.js` failed with exit code 1

**Comment by MiguelPF** [comment]
+1 The same happen in my MacOS X 10.9.5

**Comment by MiguelPF** [comment]
Made some progress towards a solution with:
```
npm install -g jspm
cd src/ && jspm install
```

Now the error is:

````
[19:08:42] Using gulpfile ~/typeslab/gulpfile.js
[19:08:42] Starting 'jspm-bundle'...
[19:08:42] Starting 'html'...
[19:08:42] Starting 'misc'...
[19:08:43] Finished 'misc' after 46 ms
[19:08:43] Finished 'html' after 72 ms
     Building the single-file sfx bundle for lib/main...

err  Error: Error loading "styles/reset.scss!post-css" at <unknown>
     Error loading "styles/reset.scss!post-css" from "lib/main" at file:/Users/miguelpousafreire/typeslab/src/lib/main.js
     Error loading "npm:caniuse-db@1.0.30000111/data" at file:/Users/miguelpousafreire/typeslab/src/jspm_packages/npm/caniuse-db@1.0.30000111/data.js
     Error loading "npm:caniuse-db@1.0.30000111/data" from "post-css" at file:/Users/miguelpousafreire/typeslab/src/post-css.js
     ENOENT, open '/Users/miguelpousafreire/typeslab/src/jspm_packages/npm/caniuse-db@1.0.30000111/data.js'
[19:08:46] 'jspm-bundle' errored after 3.35 s
[19:08:46] Error in plugin 'gulp-shell'
Message:
    Command `jspm bundle-sfx lib/main dist/bundle.js` failed with exit code 1
````

**Comment by PrasannaVenkadesh** [comment]
@MiguelPF The original error messages that i have posted and the one you have posted are same. I don't find any progress over there or difference between your message and mine. Or Am I missing anything?

**Comment by PrasannaVenkadesh** [comment]
@geelen It would be better, if you can update the README file with instructions for building this node project.

**Comment by geelen** [comment]
Yep, sorry! This is open-source but currently works-on-my-machine-only until https://github.com/jspm/npm/issues/52 is resolved. I'm going to break out my postcss workflow (which has the broken dependency) so this can be built independently.

**Comment by gyaresu** [comment]
:+1: 
```
gyaresu@shazbot:~/programming/projects/typeslab|master⚡
⇒  gulp bundle
[21:42:11] Using gulpfile ~/programming/projects/typeslab/gulpfile.js
[21:42:11] Starting 'jspm-bundle'...
     Building the single-file sfx bundle for lib/main...

err  Error: Error loading "styles/reset.scss!post-css" at <unknown>
     Error loading "styles/reset.scss!post-css" from "lib/main" at file:/Users/gyaresu/programming/projects/typeslab/src/lib/main.js
     Error loading "npm:caniuse-db@1.0.30000111/data" at file:/Users/gyaresu/programming/projects/typeslab/src/jspm_packages/npm/caniuse-db@1.0.30000111/data.js
     Error loading "npm:caniuse-db@1.0.30000111/data" from "post-css" at file:/Users/gyaresu/programming/projects/typeslab/src/post-css.js
     ENOENT, open '/Users/gyaresu/programming/projects/typeslab/src/jspm_packages/npm/caniuse-db@1.0.30000111/data.js'
         at Error (native)
[21:42:13] 'jspm-bundle' errored after 2.9 s
[21:42:13] Error in plugin 'gulp-shell'
Message:
    Command `jspm bundle-sfx lib/main dist/bundle.js` failed with exit code 1
```

**Comment by geelen** [comment]
Fixed in https://github.com/geelen/typeslab/pull/10

**Comment by geelen** [comment]
See the [Readme](https://github.com/geelen/typeslab) now, but here's what you need to get going:

```
npm install -g jspm jspm-server
jspm install
jspm-server src
```

No need to `gulp build` for development. Embrace JSPM!

**Comment by gyaresu** [comment]
![Who's Awesome? You're awesome!](http://www.whosawesome.com/images/awesome.jpg)
