### ISSUE TITLE
Option to add image

### ISSUE THREAD

**Issue by alpha0geek** [geelen/typeslab#5]
Please add an option where user can upload or put url to their own image and that will appear in final generated image. 

It will kind of make it meme generator with nice type and everything.

Thanks

**Comment by geelen** [comment]
I thought about this, but I think it'd distract from the type. There are meme generators out there already, this is for typographic posters.

Thanks for the suggestion though :)

![image](https://cloud.githubusercontent.com/assets/23264/7152481/4e30a2aa-e36f-11e4-986f-88b695e30280.png)

**Comment by alpha0geek** [comment]
take a look here https://twitter.com/quotes4ur_life/status/587101825565724673 .. that's what I mean, the problem with other meme generators is their typo sucks, so I'm sure there is use for such out there.

**Comment by geelen** [comment]
Maybe, but it's not the sort of direction I'm interested in taking this project. I don't think it can be done automatically to a decent level of quality, and I'm not trying to build something as configurable as [Canva](https://www.canva.com/) by any means. I'm happy with no images beyond emoji for now.
